### ISSUE TITLE
How to turn it on Playback Stats?

### ISSUE THREAD

**Issue by Mrakobes666** [marc2k3/foo_jscript_panel#1]
for the sake of him installed beta 1.4 Foobar2000, there is no text file with the script (((

**Comment by marc2k3** [comment]
Have a full read of this page.

https://github.com/marc2k3/foo_jscript_panel/wiki/Playback-Stats

**Comment by Mrakobes666** [comment]
I read, but did not understand how (((my English is very bad, I translated the translator, please give instructions, my friend

**Comment by marc2k3** [comment]
Those are the instructions. I cannot make it any clearer than it already is on that page.
