### ISSUE TITLE
Library changed callbacks don't return a handle_list

### ISSUE THREAD

**Issue by Wil-B** [marc2k3/foo_jscript_panel#12]
Is it possible for the following to return a handle_list of affected items?

function on_library_items_added(handle_list) {}
function on_library_items_changed(handle_list) {}
function on_library_items_removed(handle_list) {}

**Comment by marc2k3** [comment]
It should be possible. I'll take a look later on.

**Comment by marc2k3** [comment]
@Wil-B , Have you noticed before that `on_library_items_removed` gets called once per track even when removing multiple tracks at once.

I tested with this code...

```js
function on_library_items_added(handle_list) {
    console.log("added " + handle_list.Count);
}

function on_library_items_changed(handle_list) {
    console.log("changed " + handle_list.Count);
}

function on_library_items_removed(handle_list) {
    console.log("removed " + handle_list.Count);
}
```

Removing a folder with 60 items means I get this in the console 60 times...

`removed 1`

Restoring the folder shows

`added 60`

which is expected.

This is merely an observation. There is nothing I can do about it!

**Comment by marc2k3** [comment]
`v2.0.4` with these changes has been released.

https://github.com/marc2k3/foo_jscript_panel/releases

**Comment by Wil-B** [comment]
Thanks for the changes to the callbacks.

I've now thoroughly tested them. I can happily confirm they are all working well.
