### ISSUE TITLE
OrderByRelativePath() doesn't always give the required sort order

### ISSUE THREAD

**Issue by Wil-B** [marc2k3/foo_jscript_panel#16]
It seems OrderByRelativePath() uses sort_by_relative_path() rather than the more complete sort_by_relative_path_get_order().

Please consider changing OrderByRelativePath() or perhaps separately adding sort_by_relative_path_get_order().

I'm happy to try a test version, if you're inclined to do it, to see if the sort issues are resolved.

Long version:

Sort issues with the current OrderByRelativePath(), which is used with view by folder structure in Library Tree, include:

Subsongs not sorted (so anything in containers like cue files or m-TAGS are sent to playlist in wrong order unless you're lucky).

Folders like the following display in the wrong order:
Music 1
Music 2
Music

should be:
Music
Music 1
Music 2 

The subsong issue can be resolved by using a double sort:
Either:
handle_list.OrderByPath(); handle_list.OrderByRelativePath(); 
OR
handle_list.OrderByFormat(fb.TitleFormat("%subsong%"), 1); handle_list.OrderByRelativePath();

Library tree currently uses a double sort. Trouble with the double sort is that impacts on initialisation time of the view and still doesn't get that folder example right + DUI album list always gets the sorting fully correct!

**Comment by marc2k3** [comment]
If you looked closer, you'd see `sort_by_relative_path` actually calls `sort_by_relative_path_get_order` internally so the fix isn't what you think it is. I actually have no idea what's going on with that particular bit of code but it does look easy enough to workaround.

I honestly don't know why it doesn't take subsong into consideration in the first place.

**Comment by marc2k3** [comment]
Here's a component for testing...

https://github.com/marc2k3/foo_jscript_panel/wiki/16/foo_jscript_panel.dll

**Comment by Wil-B** [comment]
Thanks. It seems fine.
