### ISSUE TITLE
Added methods for window management

### ISSUE THREAD

**Issue by a1waysbeta** [marc2k3/foo_jscript_panel#17]
Because you are so careful to write a description document. Can you add some methods for window management? Although the SDK is violated, there are detailed documentation that may not be a good thing, rather than a separate addition without writing a document.

**Comment by marc2k3** [comment]
This fork already contains them...

https://github.com/TheQwertiest/foo-jscript-panel

You can download a compiled version from here..

https://github.com/TheQwertiest/CaTRoX_QWR/releases

Take care to extract just the DLL if you want to keep the docs/samples from the original component.

**Comment by TheQwertiest** [comment]
Actually, I post only dlls, since I don't want anyone to mistake my component for the official one :P
