### ISSUE TITLE
Small requests

### ISSUE THREAD

**Issue by a1waysbeta** [marc2k3/foo_jscript_panel#18]
Thank you for add plman.SortPlaylistsByName method. Now it supports sorting lists of Chinese names and works well. I have two small requests, can you modify it? Otherwise, after each update, I need to replace it manually.
(1) jssp.js line 4: %date% > $date($replace(%date%,/,-,.,-))
(2) jss*.js [// set wallpaper] add: if (ppt.showwallpaper) {...} else {g_wallpaperImg = null;};
Jsplaylist-mod has another problem.
The Panel Settings has 5 tabs, each tab has a SetSize function. Executes the corresponding SetSize function when a tab is displayed, not all of them.

**Comment by marc2k3** [comment]
I've added a window property for 1).

I don't understand the rest.
