### ISSUE TITLE
FontAwesome link is dead

### ISSUE THREAD

**Issue by Jessamynn** [marc2k3/foo_jscript_panel#20]
Just wanted to point this out, the link to the font in the "Breaking Changes" section leads to a 404.

Thankfully I still had a copy of the font from when you first added the requirement, but before I remembered that, I tried using the versions from the official FontAwesome website, which did not show up in foobar. I may not have set those up correctly, however.

**Comment by marc2k3** [comment]
Thanks for letting me know. I've updated the link on the wiki page and in the readme inside the samples folder.

https://github.com/FortAwesome/Font-Awesome/blob/fa-4/fonts/fontawesome-webfont.ttf?raw=true
