### ISSUE TITLE
I suggest use `remove_playlist_switch`

### ISSUE THREAD

**Issue by elia-is-me** [marc2k3/foo_jscript_panel#21]
https://github.com/marc2k3/foo_jscript_panel/blob/c78a13c224c0b1e392e9d7b5a5c2f6f120949b24/src/script_interface_impl.cpp#L1304

If use `plman.RemovePlaylist` to remove an active_playlist, then plman.ActivePlaylist will be an infinity number. Use `remove_playlist_switch` instead of `remove_playlist` could fix it.

**Comment by marc2k3** [comment]
I'm not changing the behaviour of the existing method - people should already be setting an active playlist manually knowing about this.

I'm happy to add it as a new method if you want.

**Comment by elia-is-me** [comment]
It's ok too.
