### ISSUE TITLE
Suggestion: Album Rating Method

### ISSUE THREAD

**Issue by CultofRobots** [marc2k3/foo_jscript_panel#27]
I would love a method for rating whole albums (e.g. %jsp_album_rating%) exactly like the track rating sample provided.

**Comment by marc2k3** [comment]
Doing this properly with a new DB for albums is too complex and it's not something I'm going to do right now.

I have a script workaround that involves updating all tracks from the same album at once but underneath, they'd still be bound "per track". If you're interested in this but want to keep track ratings at the same time, you'd have to transfer those to foo_playcount or your file tags. Let me know if you want the code snippet.

**Comment by CultofRobots** [comment]
Thanks, but I can continue using customdb for album ratings for the time being as I prefer my track ratings in jsp.
