### ISSUE TITLE
utils.InputBox

### ISSUE THREAD

**Issue by Wil-B** [marc2k3/foo_jscript_panel#28]
I tried to implement the new utils.InputBox. While some work fine, others don't.

The failures occur when the prefilled text (defaultValue) isn't edited:

var tmp = utils.InputBox(window.ID, "Proceed with the action", "Heading", prefilledText);

Prefilled text could be current artist, loaded for convenience.

Desired action when prefilledText is unedited:

OK: proceed
CANCEL: don't proceed

What actually seems to happen:

// Code option 1: FAILS
if (tmp) proceed(tmp); // BOTH OK & CANCEL proceed with the action

// Code option 2: FAILS
if (tmp != prefilledText) proceed(tmp); // OK & CANCEL BOTH FAIL to proceed with the action.
This will however work if the prefilledText is edited, but there are occasions when it is desirable to proceed with the unedited text.

I believe users should be able to correctly apply OK/CANCEL to the prefilled text or edit the text and apply OK/CANCEL.

Is there an alternative code that will work?

If not, a possibility is for the cancel button to always return an empty string "". Alternatively it could operate like the (unsupported) window.prompt() method, where cancel returns null. Code option 1 then works. It's not clear why the cancel button needs to return the defaultValue. Its value is known.

**Comment by marc2k3** [comment]
Returning an empty string on Cancel isn't go to work. Let's say I have a Last.fm script that displays my charts and I store my username. Now I want to clear my username and I open an updated InputBox to do this. At this point, the script has no idea if I intentionally cleared the text and pressed OK or changed my mind and pressed Cancel.

It can't stay as it is either so definitely needs fixing. 

Possible fixes:
1) fixed string response something like "input cancelled"
2) script error on Cancel which means putting it inside try/catch

**Comment by marc2k3** [comment]
I've updated this... see if the docs make sense to you...

https://github.com/marc2k3/foo_jscript_panel/blob/ff2d416b9b553d7bb67ed3d52b246f1878d7eb84/foo_jscript_panel/docs/Interfaces.txt#L1064L1083

**Comment by Wil-B** [comment]
It makes sense to me. Thanks for the fix. I look forward to trying it out...

**Comment by marc2k3** [comment]
New version released: https://github.com/marc2k3/foo_jscript_panel/releases
