### ISSUE TITLE
DUiTunes compatibility

### ISSUE THREAD

**Issue by cerbaire** [marc2k3/foo_jscript_panel#29]
Hi Marc,

Your work is great and I like you convert scripts of Br3tt for your plug-in.
I wonder if you would like to start an upgrade of the DUiTunes script of Br3tt also.
But if you don't want to, I understand.
Thanks for your work.

Nicolas

**Comment by marc2k3** [comment]
Nope, this component is no longer supported and the repo will be going into archive/read-only mode very soon. Another developer has a direct replacement coming out soon and I'd expect an announcement on the official foobar forums when they've finished in another month or two.
