### ISSUE TITLE
DT_WORD_ELLIPSIS & DT_END_ELLIPSIS seem to have stopped working properly?

### ISSUE THREAD

**Issue by Wil-B** [marc2k3/foo_jscript_panel#30]
Issue. With windows 10, if clipping just involves the last few letters of a sentence, DT_WORD_ELLIPSIS & DT_END_ELLIPSIS no longer add the ellipsis. They continue to work correctly on an old windows XP machine or if the extent of clipping is greater than 3 characters.

The issue occurs for me with:

fb2k 1.4; JScript Panel 2.1.6 OR wsh panel mod 1.5.6; windows 10 v1803 OS Build 17134.165.

Can you confirm the issue on recent windows 10 to exclude something bizarre about my windows 10 machine (code example below)? Or does the code have to be written differently?
If confirmed, can it be fixed within JScript Panel or is it better to hope for an external fix if the core problem lays elsewhere?

Code that shows the issue for me:

var font = gdi.Font("Segoe UI", 30, 1);
var text = "This is an example that shows the ellipsis problem";
var ww = 10;

var DT_LEFT = 0x00000000, 
    DT_CENTER = 0x00000001, 
    DT_RIGHT = 0x00000002, 
    DT_VCENTER = 0x00000004, 
    DT_SINGLELINE = 0x00000020, 
    DT_CALCRECT = 0x00000400, 
    DT_NOPREFIX = 0x00000800, 
    DT_END_ELLIPSIS = 0x00008000, 
    DT_WORD_ELLIPSIS = 0x00040000;
var END_ELLIPSIS = DT_VCENTER | DT_NOPREFIX | DT_END_ELLIPSIS;
var WORD_ELLIPSIS = DT_LEFT | DT_NOPREFIX | DT_WORD_ELLIPSIS;

function on_size() {
    ww = window.Width;
}

function on_paint(gr) {
    gr.GdiDrawText("To see issue, use width: 677 - 704:", font, RGB(0,0,0), 0, 0, ww, 40)
    gr.GdiDrawText("EndEllipsis:", font, RGB(0,0,0), 0, 40, ww, 40)
    gr.GdiDrawText(text, font, RGB(255,0,0), 0, 80, ww, 40, END_ELLIPSIS);
    gr.GdiDrawText("WordEllipsis:", font, RGB(0,0,0), 0, 120, ww, 40)
    gr.GdiDrawText(text, font, RGB(255,0,0), 0, 160, ww, 40, WORD_ELLIPSIS);
    gr.GdiDrawText("window.Width: " + ww, font, RGB(0,0,255), 0, 200, ww, 40)
    gr.GdiDrawText("DrawString (below) works correctly:", font, RGB(0,0,0), 0, 240, ww, 40)
    gr.SetTextRenderingHint(5);
    gr.DrawString(text, font, RGB(0,192,0), 0, 280, ww, 40, StringFormat(0, 0, 3));
}

function RGB(r, g, b) {return 0xff000000 | r << 16 | g << 8 | b;}

function StringFormat() {
    var a = arguments, h_align = 0, v_align = 0, trimming = 0, flags = 0;
    switch (a.length) {
        case 3: trimming = a[2];
        case 2: v_align = a[1];
        case 1: h_align = a[0];
        break; 
        default: return 0;
    }
    return (h_align << 28 | v_align << 24 | trimming << 20 | flags);
}

**Comment by marc2k3** [comment]
Seems fine on Windows 8.1 so I'll have to install Windows 10 in VMware to see if I can reproduce. I very much doubt I'll be able to do anything though!!

**Comment by marc2k3** [comment]
Reproduced.... perhaps dropping support for windows 10 is the answer! It really is a hateful piece of shit. :grin:

The best I can do for now is a script hack...

```js
var tmp = gr.CalcTextWidth(text, font) < ww ? text : text + "AAA";
gr.GdiDrawText(tmp, font, RGB(255,0,0), 0, 80, ww, 40, END_ELLIPSIS);
```

**Comment by marc2k3** [comment]
FWIW, the exact same bug happens with `$drawtextex` in `Panel Stack Splitter` and presumably `ELPlaylist` too..

```
$font(Segoe UI, 32)
$drawtextex(panel stack splitter blah blah long text ellipsis,0,0,%_width%,64,255-0-0,end_ellipsis)
```

Of course it's fine on my main Windows 8.1 system.

**Comment by Wil-B** [comment]
Yes, plus I have since noticed it with DUI playlist & es_playlist!

**Comment by marc2k3** [comment]
Well given it's a Windows 10, I'd rather not try any hacks in the component because I don't want to introduce any unwanted side effects.
