### ISSUE TITLE
Program error (?)

### ISSUE THREAD

**Issue by gritz1** [marc2k3/foo_jscript_panel#31]
After installing 2.1.7.1 on Foobar v1.4, receiving the following error:

Error: JScript Panel v2.1.7.1 (Biography Text & Album Info & Picture. www.last.fm v25072017 by kgena_ua)
Microsoft JScript runtime error:
Object doesn't support this property or method
File: main
Line: 82, Col: 9
source text only available at compile time

(carets removed on File and source code lines to allow visibility)
Wish I was a bit wiser at programming - when I look at the script it appears to be something with the background? Nah, does not sound right.
Please feel free to berate me if this is my error, and thank you for the new version.

**Comment by marc2k3** [comment]
Pretty sure kgena_ua makes scripts for WSH panel mod, not JScript Panel. 

https://code.google.com/archive/p/foo-wsh-panel-mod/downloads

Although JScript Panel is based on WSH panel mod, there have been many breaking changes meaning no scripts are going to work on both components.
