### ISSUE TITLE
JScript panel is behind other panels when used with Panel Stack Splitter

### ISSUE THREAD

**Issue by benwilson34** [marc2k3/foo_jscript_panel#32]
In this first image, the large green block on the right is the area I'm trying to use (which is a JScript panel):
![screenshot 2018-09-23 13 51 57](https://user-images.githubusercontent.com/21367650/45931218-dce6ff00-bf38-11e8-8f8b-cc6f0459c280.png)

In trying to hide the hideous scrollbar, I'm using the "Forced layout" feature of Panel Stack Splitter to push the edge of the playlist view under the JScript panel. But the playlist panel always draws on top of the JScript panel, regardless of hierarchy in the layout:
![screenshot 2018-09-23 13 54 39](https://user-images.githubusercontent.com/21367650/45931229-2899a880-bf39-11e8-81e8-4d7cded92cf2.png)

Are JScript panels always drawn first? Is there a way I can bring this panel to the front?

**Comment by marc2k3** [comment]
I wouldn't expect overlapping panels to work. Instead, put the playlist in its own PSS splitter. Then set the layout to forced. Then on the script tab...

```
$movepanel(0,0,0,$add(%_width%,17),%_height%)
```

This extends the playlist out of view on the right hand side. You may need to tinker with column alignment if content is missing when there is no scrollbar.

**Comment by marc2k3** [comment]
Since this issue is more PSS related that it is JScript Panel, I'm going to close this. You can still comment if you need to.

**Comment by benwilson34** [comment]
That's perfect, you're a wizard! I'll try more with PSS in future attempts.

Thanks for the fast response.
