### ISSUE TITLE
foobar forum comment

### ISSUE THREAD

**Issue by marc2k3** [marc2k3/foo_jscript_panel#37]
@grimes2 - your Cover flow script works fine for me on v2.2.1. Obviously you have to comment out the line that you did as per the changelog for v2.2.0. 

If you did that but still get an error, surely it must be pointing at a different line number? It couldn't possibly point at a comment for being the cause, could it?

Since I don't post there any more, could you do me a favour and post a reminder in the foobar thread that any issues can be reported on here on Github. Even the Configuration Window has a link...

![Untitled](https://user-images.githubusercontent.com/34617027/54486343-ee251e80-487e-11e9-898d-4548d8ac6925.png)

**Comment by grimes2** [comment]
The error is strange. It is pointing to the same line number, that I comment out before. Is it possible, that two instances of the script are loaded and an old one is still active?

**Comment by marc2k3** [comment]
You can check the Console on startup to see how many JScript Panel instances there are.

Example...

```
Components loaded in: 0:00.006877
Configuration read in: 0:00.001920
foobar2000 v1.4.3 [portable]
Watching: E:\Music
JScript Panel v2.2.1 (CoverFlow View (stand alone script version) v1.5.1 by Br3tt aka Falstaff >> http://br3tt.deviantart.com): initialised in 17 ms
JScript Panel v2.2.1 (JS Smooth Playlist Manager v2018-mod by Br3tt aka Falstaff): initialised in 12 ms
JScript Panel v2.2.1 (Track Info + Seekbar + Buttons by marc2003): initialised in 14 ms
User Interface initialized in: 0:00.090574
FFmpeg version: 3.4.5
Startup time : 0:00.125612
```

**Comment by grimes2** [comment]
There were indeed two instances of der Coverflow script running.

This works for me:

- Remove panel in CUI Layout
- Remove old version of JScript Panel
- Restart foobar2000
- Add version 2.2.1 of JScript Panel
- Add panel in CUI Layout
-  Insert Coverflow script

**Comment by marc2k3** [comment]
I've just applied a few fixes to that script...

https://gist.github.com/marc2k3/72b47334d8b02b26689ff7b168eb77bc

-now you can drag files on to it - previously it would error because it's using outdated code
-you can access the normal right click menu/access to the Configure option when not right clicking on a cover.

**Comment by MojoBass** [comment]
> 
> 
> I've just applied a few fixes to that script...
> 
> https://gist.github.com/marc2k3/72b47334d8b02b26689ff7b168eb77bc
> 
> -now you can drag files on to it - previously it would error because it was using outdated code
> -you can access the normal right click menu when not right clicking on a cover.
> 
> edit; Thanks for posting the reminder on the forum.

Hello Marc, the link [https://gist.github.com/marc2k3/72b47334d8b02b26689ff7b168eb77bc](url) seems not to work any more. I very much like the script and wanted to recommend that for this request:[https://hydrogenaud.io/index.php/topic,116669.msg970670.html#msg970670](url).
Is there any reason why the coverflow script is not part of your 'managed' scripts like js-smooth  or jsplaylist-mod? I think it would be worth... best regards, MojoBass

**Comment by marc2k3** [comment]
I'm not taking on any more 3rd party scripts. Updating them is an absolute nightmare.

**Comment by MojoBass** [comment]
Ok, I would have guessed that this is a real nightmare. And thanks for doing that for the 3rd party scripts you already have taken!!
As the above link is not working: any issue from your side if I share my local copy of your update of the coverflow script?

**Comment by marc2k3** [comment]
Do what you like.
