### ISSUE TITLE
Question about image cache

### ISSUE THREAD

**Issue by leo870319** [marc2k3/foo_jscript_panel#39]
I found JSSB will reset image cache after foobar has been restart.
Is there any way to make JSSB re-load image cache that previously stored instead of resetting it every time? 
This will be very helpful for people who use network drive to store their music. It takes a lot of time to reload every album images.
  
Thank you.

**Comment by marc2k3** [comment]
That should not be the case. If you check the foobar2000 profile folder (`%appdata%\roaming\foobar2000` or the program folder in portable mode) and look inside the `js_smooth_cache` folder, the last modified timestamps of the files should be from the first time you ran the script. These small images are then used on every subsequent run. They still take time to load so they're never going to be instant, not even from a SSD.

**Comment by leo870319** [comment]
I already checked js_smooth_cache folder,new files will be added every time I restart foobar2000 (old files are still there).
It seems that the script does not run as it should be.

**Comment by marc2k3** [comment]
Well you do have to scroll through all albums for cache files to be generated. Anything that hasn't been viewed or scrolled past too quickly won't have a cached file. Also, there were bugs in early versions but I'm pretty sure I fixed those last year. Make sure you're running the latest version.

**Comment by leo870319** [comment]
GOT IT. thank you,
