### ISSUE TITLE
Track Info + Seekbar + Buttons

### ISSUE THREAD

**Issue by a1waysbeta** [marc2k3/foo_jscript_panel#40]
Can you add an option to blur the background using the cover color? and button using font button.

**Comment by marc2k3** [comment]
This uses the album art for the entire background using StackBlur.

```js
// ==PREPROCESSOR==
// @name "Track Info + Seekbar + Buttons"
// @author "marc2003"
// @import "%fb2k_component_path%samples\complete\js\lodash.min.js"
// @import "%fb2k_component_path%samples\complete\js\helpers.js"
// @import "%fb2k_component_path%samples\complete\js\panel.js"
// @import "%fb2k_component_path%samples\complete\js\seekbar.js"
// ==/PREPROCESSOR==

var colours = {
	buttons : _.RGB(255, 255, 255),
	background : _.RGB(30, 30, 30),
	title : _.RGB(255, 255, 255),
	artist : _.RGB(240, 240, 240),
	time : _.RGB(240, 240, 240),
	seekbar_background : _.RGB(160, 160, 160),
	seekbar_progress : _.RGB(255, 255, 255),
	seekbar_knob : _.RGB(196, 30, 35)
};

var tfo = {
	artist : fb.TitleFormat('%artist%'),
	title : fb.TitleFormat('%title%'),
	playback_time : fb.TitleFormat('%playback_time%  '),
	length : fb.TitleFormat('  %length%')
};

//////////////////////////////////////////////////////////////

var panel = new _.panel();
var seekbar = new _.seekbar(0, 0, 0, 0);
var buttons = new _.buttons();
var img = null;
var back = null;
var bs = _.scale(24);
on_playback_new_track(fb.GetNowPlaying());

buttons.update = function () {
	var y = Math.round((panel.h - bs) / 2);
	this.buttons.stop = new _.button(panel.w - LM - (bs * 8), y, bs, bs, {normal : _.chrToImg(chars.stop, colours.buttons)}, function () { fb.Stop(); }, 'Stop');
	this.buttons.previous = new _.button(panel.w - LM - (bs * 7), y, bs, bs, {normal : _.chrToImg(chars.prev, colours.buttons)}, function () { fb.Prev(); }, 'Previous');
	this.buttons.play = new _.button(panel.w - LM - (bs * 6), y, bs, bs, {normal : !fb.IsPlaying || fb.IsPaused ? _.chrToImg(chars.play, colours.buttons) : _.chrToImg(chars.pause, colours.buttons)}, function () { fb.PlayOrPause(); }, !fb.IsPlaying || fb.IsPaused ? 'Play' : 'Pause');
	this.buttons.next = new _.button(panel.w - LM - (bs * 5), y, bs, bs, {normal : _.chrToImg(chars.next, colours.buttons)}, function () { fb.Next(); }, 'Next');
	this.buttons.console = new _.button(panel.w - LM - (bs * 3), y, bs, bs, {normal : _.chrToImg(chars.console, colours.buttons)}, function () { fb.ShowConsole(); }, 'Console');
	this.buttons.search = new _.button(panel.w - LM - (bs * 2), y, bs, bs, {normal : _.chrToImg(chars.search, colours.buttons)}, function () { fb.RunMainMenuCommand('Library/Search'); }, 'Library Search');
	this.buttons.preferences = new _.button(panel.w - LM - bs, y, bs, bs, {normal : _.chrToImg(chars.preferences, colours.buttons)}, function () { fb.ShowPreferences(); }, 'Preferences');
}

function on_size() {
	panel.size();
	seekbar.x = Math.round(panel.w * 0.22);
	seekbar.w = panel.w - seekbar.x - _.scale(280);
	seekbar.h = _.scale(12);
	seekbar.y = (panel.h - seekbar.h) / 2;
	buttons.update();
}

function on_paint(gr) {
	gr.FillSolidRect(0, 0, panel.w, panel.h, colours.background);
	if (fb.IsPlaying) {
		if (back) {
			_.drawImage(gr, back, 0, 0, panel.w, panel.h, image.crop, null, 150);
		}
		if (img) {
			_.drawImage(gr, img, 0, 0, panel.h, panel.h, image.centre);
		}
		buttons.paint(gr);
		gr.FillSolidRect(seekbar.x, seekbar.y, seekbar.w + _.scale(6), seekbar.h, colours.seekbar_background);
		gr.GdiDrawText(tfo.title.Eval(), panel.fonts.title, colours.title, panel.h + 10, 0, seekbar.x - panel.h - _.scale(60), panel.h * 0.6, LEFT);
		gr.GdiDrawText(tfo.artist.Eval(), panel.fonts.normal, colours.artist, panel.h + 10, panel.h * 0.3, seekbar.x - panel.h - _.scale(60), panel.h * 0.7, LEFT);
		gr.SetSmoothingMode(2);
		if (fb.PlaybackLength > 0) {
			var pos = seekbar.pos();
			gr.FillSolidRect(seekbar.x, seekbar.y, pos, seekbar.h, colours.seekbar_progress);
			gr.FillSolidRect(seekbar.x + pos, seekbar.y, _.scale(6), seekbar.h, colours.seekbar_knob);
			gr.GdiDrawText(tfo.playback_time.Eval(), panel.fonts.normal, colours.time, seekbar.x - _.scale(45), 0, _.scale(45), panel.h, RIGHT);
			gr.GdiDrawText(tfo.length.Eval(), panel.fonts.normal, colours.time, seekbar.x + seekbar.w + _.scale(6), 0, _.scale(45), panel.h, LEFT);
		}
	} else {
		buttons.paint(gr);
		gr.FillSolidRect(seekbar.x, seekbar.y, seekbar.w + _.scale(6), seekbar.h, colours.seekbar_background);
	}
	gr.DrawRect(seekbar.x, seekbar.y, seekbar.w + _.scale(6), seekbar.h, 1, colours.seekbar_progress);
}

function on_playback_new_track(metadb) {
	if (!metadb) {
		return;
	}
	_.dispose(img, back);
	img = utils.GetAlbumArtV2(metadb, 0);
    if (img) {
        back = img.Clone(0, 0, img.Width, img.Height);
        back.StackBlur(50);
    }
	window.Repaint();
}

function on_playback_edited() {
	window.Repaint();
}

function on_playback_seek() {
	seekbar.playback_seek();
}

function on_playback_stop() {
	buttons.update();
	window.Repaint();
}

function on_playback_pause() {
	buttons.update();
	window.Repaint();
}

function on_playback_starting() {
	buttons.update();
	window.Repaint();
}

function on_mouse_wheel(s) {
	if (seekbar.wheel(s)) {
		return;
	}
	if (s == 1) {
		fb.VolumeUp();
	} else {
		fb.VolumeDown();
	}
}

function on_mouse_move(x, y) {
	if (buttons.move(x, y)) {
		return;
	}
	seekbar.move(x, y);
}

function on_mouse_leave() {
	buttons.leave();
}

function on_mouse_lbtn_down(x, y) {
	seekbar.lbtn_down(x, y);
}

function on_mouse_lbtn_up(x, y) {
	if (buttons.lbtn_up(x, y)) {
		return;
	}
	if (seekbar.lbtn_up(x, y)) {
		return;
	}
	fb.RunMainMenuCommand('View/Show now playing in playlist');
}

function on_mouse_rbtn_up(x, y) {
	return panel.rbtn_up(x, y);
}
```

**Comment by a1waysbeta** [comment]
Perfect~ Will you consider using a font button instead of a picture button and adding a volume bar?

**Comment by marc2k3** [comment]
The script already uses a function named `_.chrToImg` which converts a single character and colour to an image which can be used in the buttons.

It uses fontawesome by default but I've updated it just now to accept custom fonts as the 3rd argument.

```js
var img = _.chrToImg(char, _.RGB(255, 0, 0); // red using fontawesome

var font = gdi.Font("guifx v2 transports", 48);
var img2 = _.chrToImg(char, _.RGB(0, 0, 0), font); // black using custom font
```

You'll need this updated `samples\complete\js\helpers.js` file for custom fonts..

https://raw.githubusercontent.com/marc2k3/foo_jscript_panel/master/foo_jscript_panel/samples/complete/js/helpers.js

**Comment by a1waysbeta** [comment]
awkward. The icon is already a font icon instead of a picture~
I am adding rating, and modifying the seekbar. But I won't add the volume and play order buttons. Can you replace the Preferences and Search buttons with the play order and volume for me? (volume button: left click to mute, mouse wheel to adjust volume)
[https://imgur.com/125rv3A](url)

**Comment by marc2k3** [comment]
You can already change the volume with the mousewheel. You can change the rest yourself. Don't be so lazy!

**Comment by a1waysbeta** [comment]
The modified code, when changing the volume, the cpu rises. Ask for your help. At the same time, I want to add a function to lock the height of the panel.
`// ==PREPROCESSOR==
// @name "Track Info + Seekbar + Buttons"
// @author "marc2003"
// @import "%fb2k_component_path%samples\complete\js\lodash.min.js"
// @import "%fb2k_component_path%samples\complete\js\helpers.js"
// @import "%fb2k_component_path%samples\complete\js\panel.js"
// @import "%fb2k_component_path%samples\complete\js\seekbar.js"
// @import "%fb2k_component_path%samples\complete\js\volume.js"
// ==/PREPROCESSOR==

var colours = {
	buttons : _.RGB(255, 255, 255),
	background : _.RGB(30, 30, 30),
	title : _.RGB(255, 255, 255),
	artist : _.RGB(240, 240, 240),
	time : _.RGB(240, 240, 240),
	seekbar_background : _.RGB(160, 160, 160),
	seekbar_progress : _.RGB(255, 255, 255),
	// seekbar_knob : _.RGB(196, 30, 35),
	volume_background : _.RGB(160, 160, 160),
	volume_progress : _.RGB(255, 255, 255),
	volume : _.RGB(240, 240, 240)
};

var tfo = {
	artist : fb.TitleFormat('%artist%'),
	title : fb.TitleFormat('%title%'),
	playback_time : fb.TitleFormat('%playback_time%  '),
	length : fb.TitleFormat('  %length%')
};

var titleFont = gdi.Font("Microsoft Yahei UI", _.scale(10), 1);
var artistFont = gdi.Font("Microsoft Yahei UI", _.scale(10));
var timeFont = gdi.Font("Microsoft Yahei UI", _.scale(9));
var fontAssets = gdi.Font("Segoe MDL2 Assets", _.scale(40));
var buttonsFont = gdi.Font("Segoe UI", _.scale(22));

var chars = {
	prev : '\uE100',
	next : '\uE101',
	play : '\uE102',
	pause : '\uE103',
	stop : '\uE004',
	lyric : '\uE8D6',
};

//////////////////////////////////////////////////////////////

var panel = new _.panel();
var seekbar = new _.seekbar(0, 0, 0, 0);
var buttons = new _.buttons();
var volume = new _.volume(0, 0, 100, 0);
var img = null;
var back = null;
var bs = _.scale(24);
on_playback_new_track(fb.GetNowPlaying());

buttons.update = function () {
	var y = Math.round((panel.h - bs) / 2);
	this.buttons.stop = new _.button(panel.w - LM - (bs * 5), y, bs, bs, {normal : _.chrToImg(chars.stop, colours.buttons, fontAssets)}, function () { fb.Stop(); }, 'Stop');
	this.buttons.previous = new _.button(panel.w - LM - (bs * 4), y, bs, bs, {normal : _.chrToImg(chars.prev, colours.buttons, fontAssets)}, function () { fb.Prev(); }, 'Previous');
	this.buttons.play = new _.button(panel.w - LM - (bs * 3), y, bs, bs, {normal : !fb.IsPlaying || fb.IsPaused ? _.chrToImg(chars.play, colours.buttons, fontAssets) : _.chrToImg(chars.pause, colours.buttons, fontAssets)}, function () { fb.PlayOrPause(); }, !fb.IsPlaying || fb.IsPaused ? 'Play' : 'Pause');
	this.buttons.next = new _.button(panel.w - LM - (bs * 2), y, bs, bs, {normal : _.chrToImg(chars.next, colours.buttons, fontAssets)}, function () { fb.Next(); }, 'Next');
	// this.buttons.lyric = new _.button(panel.w - LM - (bs), y, bs, bs, {normal : _.chrToImg(chars.lyric, colours.buttons, fontAssets2)}, function () { fb.RunMainMenuCommand('View/ESLyric/Show the Desktop Lyric'); }, 'Deskop Lyric');
	this.buttons.lyric = new _.button(panel.w - LM - (bs), y, bs, bs, {normal : _.chrToImg("LRC", colours.buttons, buttonsFont)}, function () { fb.RunMainMenuCommand('View/ESLyric/Show the Desktop Lyric'); }, 'Deskop Lyric');
}

function on_size() {
	panel.size();
	seekbar.x = Math.round(panel.w * 0.25);
	seekbar.w = panel.w - seekbar.x - _.scale(325);
	seekbar.h = _.scale(2);
	seekbar.y = (panel.h - seekbar.h) / 2;
	volume.x = seekbar.x + seekbar.w + _.scale(51);
	volume.w = _.scale(80);
	volume.h = _.scale(2);
	volume.y = (panel.h - volume.h) / 2;
	buttons.update();
}

function on_paint(gr) {
	gr.FillSolidRect(0, 0, panel.w, panel.h, colours.background);
	if (fb.IsPlaying) {
		if (back) {
			_.drawImage(gr, back, 0, 0, panel.w, panel.h, image.crop, null, 150);
		}
		if (img) {
			_.drawImage(gr, img, 0, 0, panel.h, panel.h, image.centre);
		}
		buttons.paint(gr);
		gr.FillSolidRect(seekbar.x, seekbar.y, seekbar.w + _.scale(6), seekbar.h, colours.seekbar_background);
		gr.GdiDrawText(tfo.title.Eval(), titleFont, colours.title, panel.h + 10, 0, seekbar.x - panel.h - _.scale(55), panel.h * 0.6, LEFT);
		gr.GdiDrawText(tfo.artist.Eval(), artistFont, colours.artist, panel.h + 10, panel.h * 0.3, seekbar.x - panel.h - _.scale(55), panel.h * 0.7, LEFT);
		gr.SetSmoothingMode(2);
		if (fb.PlaybackLength > 0) {
			var pos = seekbar.pos();
			gr.FillSolidRect(seekbar.x, seekbar.y, pos, seekbar.h, colours.seekbar_progress);
			gr.FillEllipse(seekbar.x + pos - 6.5, seekbar.y - _.scale(3), _.scale(7.5), _.scale(7.5), colours.seekbar_progress);
			gr.GdiDrawText(tfo.playback_time.Eval(), timeFont, colours.time, seekbar.x - _.scale(45), 0, _.scale(45), panel.h, RIGHT);
			gr.GdiDrawText(tfo.length.Eval(), timeFont, colours.time, seekbar.x + seekbar.w + _.scale(6), 0, _.scale(45), panel.h, LEFT);
		}
	} else {
		buttons.paint(gr);
		gr.FillSolidRect(seekbar.x, seekbar.y, seekbar.w + _.scale(6), seekbar.h, colours.seekbar_background);
	}
	// gr.DrawRect(seekbar.x, seekbar.y, seekbar.w + _.scale(6), seekbar.h, 1, colours.seekbar_progress);
	gr.FillSolidRect(volume.x, volume.y, volume.w, volume.h, colours.volume_background);
	gr.FillSolidRect(volume.x, volume.y, volume.pos(), volume.h, colours.volume_progress);
	gr.SetSmoothingMode(2);
	gr.FillEllipse(volume.x + volume.pos() - 6.5, volume.y - _.scale(3), _.scale(7.5), _.scale(7.5), colours.volume_progress);
	gr.GdiDrawText(fb.Volume.toFixed(2) + ' dB', timeFont, colours.volume, volume.x + volume.w + _.scale(6), 0, _.textWidth('-100.00 dB', timeFont), panel.h, LEFT);
}

function on_playback_new_track(metadb) {
	if (!metadb) {
		return;
	}
	_.dispose(img, back);
	img = utils.GetAlbumArtV2(metadb, 0);
	if (img) {
		back = img.Clone(0, 0, img.Width, img.Height);
		back.StackBlur(50);
	}
	window.Repaint();
}

function on_playback_edited() {
	window.Repaint();
}

function on_playback_seek() {
	seekbar.playback_seek();
}

function on_playback_stop() {
	buttons.update();
	window.Repaint();
}

function on_playback_pause() {
	buttons.update();
	window.Repaint();
}

function on_playback_starting() {
	buttons.update();
	window.Repaint();
}

function on_volume_change() {
	window.Repaint();
}

function on_mouse_wheel(s) {
	if (seekbar.wheel(s)) {
		return;
	}
	if (s == 1) {
		fb.VolumeUp();
	} else {
		fb.VolumeDown();
	}
}

function on_mouse_move(x, y) {
	if (buttons.move(x, y)) {
		return;
	}
	seekbar.move(x, y);
	volume.move(x, y);
}

function on_mouse_leave() {
	buttons.leave();
}

function on_mouse_lbtn_down(x, y) {
	seekbar.lbtn_down(x, y);
	volume.lbtn_down(x, y);
}

function on_mouse_lbtn_up(x, y) {
	if (buttons.lbtn_up(x, y)) {
		return;
	}
	if (volume.lbtn_up(x, y)) {
		return;
	}
	if (seekbar.lbtn_up(x, y)) {
		return;
	}
	fb.RunMainMenuCommand('View/Show now playing in playlist');
}

function on_mouse_rbtn_up(x, y) {
	return panel.rbtn_up(x, y);
}`
