### ISSUE TITLE
Alt key down is not immediately recognized

### ISSUE THREAD

**Issue by kbuffington** [marc2k3/foo_jscript_panel#42]
Not sure when this problem cropped up, but I'm seeing an issue where the Alt key doesn't register as being down until a key up event is seen. I think I was previously using 2.2.0 but could be way off. Still happening with 2.2.2.2.

```
var VK_CONTROL = 0x11;
var VK_MENU = 0x12; // ALT
var VK_LMENU = 0xA4; // Left MENU key (Left Alt)
var VK_RMENU = 0xA5; // Right MENU key (Right Alt)

function log(vkey) {
    console.log((vkey ? 'vkey: ' + vkey + ' - ' : '') +
        'Ctrl:', utils.IsKeyPressed(VK_CONTROL), 
        'Alt:', utils.IsKeyPressed(VK_MENU) 
        //,' (Left:', utils.IsKeyPressed(VK_LMENU),
        //'Right:', utils.IsKeyPressed(VK_RMENU) + ')'
        );
}

function on_mouse_wheel(delta) {
    log();
}

function on_key_down(vkey) {
    log(vkey);
}
```

I noticed this while trying to figure out why my alt key usually didn't register when scrolling the mouse wheel. 

Behavior I'm seeing: If I hold down Alt, it's false, until I release it and _then_ I get a key_down event. 
Also, if I hold down Alt (and keep it held the entire time), it's false, then if I hold down Ctrl, Alt is still false, then if I release Ctrl, Alt is now true, then if I hold down Ctrl, Alt is still true.

**Comment by marc2k3** [comment]
Seems fine for me. Remember that anything defined in your main preferences>Keyboard shortcuts will not be passed to the component via on_key_down.

Are you sure your ALT key is not doing something there? Have you tested this on a clean portable install?

**Comment by kbuffington** [comment]
Nothing out of the ordinary in the keyboard shortcuts. I'm running foobar 1.4.6 at the moment, so maybe that's the issue.

Other possible issue is that right now I'm running foobar in a VM on OSX. I had seen similar odd behavior (that I hadn't pinned down to the Alt key) on my Windows machine at home but didn't look into it until today. I'll give that a test tonight with a portable install.

**Comment by kbuffington** [comment]
Just verified the behavior outside of foobar with the Windows On Screen keyboard. Must be a VM issue. Closing.
