### ISSUE TITLE
aw, crashed ;( on mp3 file with strange tags

### ISSUE THREAD

**Issue by gitgetgot** [marc2k3/foo_jscript_panel#43]
Hello,

I installed foobar2000 version 1.5 beta 7 on Win7 64bit and
```
JScript Panel v2.1.8 by marc2003
Based on WSH Panel Mod by T.P. Wang

Build: 08:11:18, Oct 12 2018
Columns UI SDK Version: 6.5
```
When I play the attached file [test.zip](https://github.com/marc2k3/foo_jscript_panel/files/3464380/test.zip), this error comes up:
```
Error: JScript Panel v2.1.8 (Last.fm Similar Artists + User Charts + Recent Tracks by marc2003)
Laufzeitfehler in Microsoft JScript:
Ungültige(r) Dateiname oder -nummer.
File: C:\f2k\user-components\foo_jscript_panel\samples\complete\js\helpers.js
Line: 130, Col: 4
<source text only available at compile time>

Error: JScript Panel v2.1.8 (Thumbs by marc2003)
Laufzeitfehler in Microsoft JScript:
Ungültige(r) Dateiname oder -nummer.
File: C:\f2k\user-components\foo_jscript_panel\samples\complete\js\helpers.js
Line: 130, Col: 4
<source text only available at compile time>
```
When I play that file in foobar version 1.4.6, everything is ok.

FYI, thank you for your great software!

**Comment by marc2k3** [comment]
SInce whatever "tags" the file contains aren't readable in other players/tagging apps like mp3tag but appear corrupted in v1.5, just remove them.

Right click the file in a playlist, open the Properties dialog, click the Tools button>Remove tags.
