### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by grimes2** [marc2k3/foo_jscript_panel#46]
The Color Picker doesn't remember the color chosen after next start. What do I have to modify to keep the color? (question on behalf of tedgo)

**Comment by marc2k3** [comment]
Not sure what you mean? It takes a "default_colour" argument which you can store with window.GetProperty/window.SetProperty.

I've just adjusted the already included ColourPicker sample to do exactly that.

```js
// ==PREPROCESSOR==
// @name "ColourPicker"
// @author "marc2003"
// @import "%fb2k_component_path%docs\flags.txt"
// @import "%fb2k_component_path%docs\helpers.txt"
// ==/PREPROCESSOR==

var colour = window.GetProperty("COLOUR.PICKER", RGB(255, 0, 0));
var font = gdi.Font('Segoe UI', 16, 1);

function on_paint(gr) {
	gr.FillSolidRect(0, 0, window.Width, window.Height, colour);
	gr.FillSolidRect(0, 0, window.Width, 24, RGB(0, 0, 0));
	gr.GdiDrawText('Click to open ColourPicker', font, RGB(255, 255, 255), 0, 0, window.Width, 24, DT_CENTER);
}

function on_mouse_lbtn_up() {
	colour = utils.ColourPicker(window.ID, colour);
	window.SetProperty("COLOUR.PICKER", colour);
	window.Repaint();
}
```

Now the previously selected colour is remembered after reloading the panel/restarting foobar.

**Comment by grimes2** [comment]
Sorry I mean the "Custom colors". The 16 custom colour were not remembered.

**Comment by marc2k3** [comment]
I see. Obviously there is nothing you can do about it in script. The component would need updating. Either a new utils.ColourPicker2 method could be added that accepts/returns arrays or the component could remember the colours itself. I'll look in to it.

**Comment by marc2k3** [comment]
Just checked and the default UI colour picker only remembers custom colours until foobar is closed. And Coloumns UI doesn't remember at all. Remembering for the session without writing any configuration does make it far easier think about.
