### ISSUE TITLE
GdiDrawText character orientation for Japanese language on certain font

### ISSUE THREAD

**Issue by zhteh** [marc2k3/foo_jscript_panel#48]
![foobar200](https://user-images.githubusercontent.com/3736219/69151514-b9f0b480-0b15-11ea-970a-359a7ee41d03.jpg)

Hi, was playing around with different font styles and notice a strange behavior in GdiDrawText.
As you can see in bottom circle, the orientation of the Japanese character is incorrect compare to the red circle above. Any idea why?

**Comment by marc2k3** [comment]
Sorry, I have no idea. What font is it and what is the playlist viewer displaying it correctly?

**Comment by zhteh** [comment]
Hi, Sorry I think the problem is at my end. Seems like there are 2 font names of the same type eg. @Meiryo and Meiryo. The one with @ will turn it side way.

**Comment by marc2k3** [comment]
No problemo.
