### ISSUE TITLE
ListenBrainz cache not clearing after submission

### ISSUE THREAD

**Issue by smoralis** [marc2k3/foo_jscript_panel#6]
The cache file listenbrainz.json is not cleared after successful submission.

Typo ( arguments backward ) in listenbrainz.js
#158 _.save(JSON.stringify(_.drop(this.open_cache(), this.max_listens)), this.cache_file);

should be
#158 _.save(this.cache_file, JSON.stringify(_.drop(this.open_cache(), this.max_listens)));

**Comment by marc2k3** [comment]
Good spot, thanks.
