### ISSUE TITLE
Crash with previous version  'good' code

### ISSUE THREAD

**Issue by sjs-1956** [marc2k3/foo_jscript_panel#7]
GJScript Panel v2.0.1-Beta1
Getting 'Object doesn't support this property or method' with line;
if (front_names.some(function(v) {return fname.indexOf(v) >= 0; })) {

front_names is an array that I'm searching for a string entry

**Comment by marc2k3** [comment]
Check the `Script Engine` setting is set to `Chakra` - this is required for `some`.

https://github.com/marc2k3/foo_jscript_panel/wiki/Configuration-Window#script-engine

**Comment by sjs-1956** [comment]
Hi Marc
Yep that fixed it. Thanks for the swift responce and for your continued work on this great panel.

Regards
Steve Saunders

________________________________

**Comment by marc2k3** [comment]
Unfortunately it's a little niggle of the upgrade process. All new panels default to `Chakra` but any existing panels that were part of an existing layout upgraded from `v1.x` default to `JScript`.
