### ISSUE TITLE
Error: JScript Panel v2.0.1.2

### ISSUE THREAD

**Issue by a1waysbeta** [marc2k3/foo_jscript_panel#9]
Error: JScript Panel v2.0.1.2 (JS Smooth Browser v2018-mod by Br3tt aka Falstaff)
JavaScript 运行时错误:
无法获取未定义或 null 引用的属性“Width”
File: D:\Portable Soft\foobar2000\user-components\foo_jscript_panel\samples\js-smooth\js\JScommon.js
Line: 1014, Col: 2
<source text only available at compile time>
----------------
Error: JScript Panel v2.0.1.2 (JS Smooth Playlist v2018-mod by Br3tt aka Falstaff)
JavaScript 运行时错误:
无法获取未定义或 null 引用的属性“Width”
File: D:\Portable Soft\foobar2000\user-components\foo_jscript_panel\samples\js-smooth\js\JScommon.js
Line: 1014, Col: 2
<source text only available at compile time>

**Comment by marc2k3** [comment]
That's strange. I did make some changes but I fully tested them across several different installs of Windows??

Can you open `user-components\foo_jscript_panel\samples\js-smooth\js\JScommon.js` and on line 1013 where it says 

```
	var img = gdi.Image(source);
```

replace it with...

```
	var img = gdi.Image(source);
	if (!img) {
		console.log("gdi.Image failed: " + source);
		console.log(utils.FileTest(source, "e") ? "File exists." : "File does not exist.");
		return;
	}
```

Delete the `js_smooth_cache` folder in your profile and reload the script. Then post any errors from the `Console`.

**Comment by a1waysbeta** [comment]
After the replacement it works well.
gdi.Image failed: F:\迅雷下载\Demi (Deluxe)\._拿来音乐.jpg
File exists.

**Comment by marc2k3** [comment]
Well I tested the folder/filename and the `gdi.Image` function has no problem with it so I guess it doesn't like the actual contents of your file. I'll update the script to skip such files. Thanks.
